export interface IBaseEntity {
  /**
   * The unique incremental identifier of the record, auto-generated by the DB.
   */
  id: number;

  /**
   * Date of creation of the record.
   */
  createdAt: Date;

  /**
   * Date of last update of the record
   */
  updatedAt: Date;

  /**
   * Date of deletion of the record.
   */
  deletedAt: Date | null;

  /**
   * Version autogenerated by typeorm. Increase every time the record is updated.
   */
  version: number;
}
